### Create a new user
POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "email" : "new10@test.com",
    "fullname": "new10",
    "username": "new10",
    "password": "new10"

}

### Sign in a user
POST http://localhost:3000/users/signin
Content-Type: application/json

{
    "email" : "new10@test.com",
    "password": "new10"
}

### Get the currently signed in user
GET http://localhost:3000/users/whoami
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwLCJ1c2VybmFtZSI6Im5ldyIsImVtYWlsIjoibmV3QHRlc3QuY29tIiwiaWF0IjoxNzA0NzIwMzgxLCJleHAiOjE3MDQ4MDY3ODF9.XkTrHcdoAbKEuEucxny9O1v31CUsLgrGUgon-Og7otg



### Find a particular user with a given id
GET http://localhost:3000/users/1

### Find all users with a given email
GET http://localhost:3000/users?email=a@a.com

### Delete the currently logedin user
DELETE http://localhost:3000/users/delaccount
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjExLCJ1c2VybmFtZSI6Im5ldzEwIiwiZW1haWwiOiJuZXcxMEB0ZXN0LmNvbSIsImlhdCI6MTcwNDc5NTkzNSwiZXhwIjoxNzA0ODgyMzM1fQ.TNdjntUYAGPY8VMVGo-gL-TAe5FkGfnj7MUmVdVcpPE

### Update a user 
PATCH http://localhost:3000/users/edit
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsInVzZXJuYW1lIjoiMyIsImVtYWlsIjoiM0B0ZXN0My5jb20iLCJpYXQiOjE3MDQ3MjAxNzAsImV4cCI6MTcwNDgwNjU3MH0.MH5kj3foyO8wF5N_QW8usiS5XaYd1S0OsWEwxBN5ag4
Content-Type: application/json

{
    "email": "abcd@abcd.com"
}

### Change user password
PATCH http://localhost:3000/users/changePass
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwLCJ1c2VybmFtZSI6Im5ldyIsImVtYWlsIjoibmV3QHRlc3QuY29tIiwiaWF0IjoxNzA0NzI0MTAxLCJleHAiOjE3MDQ4MTA1MDF9.PnkTOhBeCImX0J0mQim-sSRj_lUnmPclx75UoslBQyk
Content-Type: application/json

{
    "currentPassword" : "new",
    "newPassword" : "new2"
}